---
- name: playbook for pull the repo
  hosts: localhost
  vars:
    tenant: gsxxcc
  tasks:
    - name: Check the git repo status 
      shell: chdir=/root/testgit git status
      register: result 

    - name: Addiing files to repo
      shell: chdir=/root/testgit git add -A
      when: result.stdout.find("modified") !=-1
      register: gitaddresult
    
    - name: Commit changes 
      shell: chdir=/root/testgit git commit -m test
      #when: ('"Untracked" in result') or ('"modified" in result')
      when: gitaddresult is defined
     
    - name: pull changes
      shell: chdir=/root/testgit git pull git@github.com:vinodmv555/testgit.git
